package com.amazonaws.dynamo.Bean;

public class CustomerProfileFields {
    public static String __customerProfileVersion = "__customerProfileVersion";
    public static String _restrictedRM_available_to_useFlag = "_restrictedRM_available_to_useFlag";
    public static String accountClosedFlag = "accountClosedFlag";
    public static String accountConverted = "accountConverted";
    public static String accountRevalidationReqdFlag2 = "accountRevalidationReqdFlag2";
    public static String acctCreatedByPerfectPickFlag3 = "acctCreatedByPerfectPickFlag3";
    public static String addr1 = "addr1";
    public static String addr2 = "addr2";
    public static String adminCreatedAcct = "adminCreatedAcct";
    //    public long adminFlags;
    public static String affiliatePaid = "affiliatePaid";
    public static String ageVerifiedFlag = "ageVerifiedFlag";
    public static String amlDepositThresholdReachedFlag3 = "amlDepositThresholdReachedFlag3";
    public static String amlDocsInProgressFlags3 = "amlDocsInProgressFlags3";
    public static String amlSuspendedFlags3 = "amlSuspendedFlags3";
    public static String antiMoneyLaundryVerifiedFlags3 = "antiMoneyLaundryVerifiedFlags3";
    public static String authVerifiedFlag = "authVerifiedFlag";
    public static String autoAcceptPriceChangesFlag3 = "autoAcceptPriceChangesFlag3";
    public static String autoAddressFlag2 = "autoAddressFlag2";
    public static String autoConvertBuyIn = "autoConvertBuyIn";
    public static String autoConvertWinnings = "autoConvertWinnings";
    //    public static  ObjectNode   balance                              =    ObjectNodeSchema   "balance" ;
    public static String bannedByRegulator = "bannedByRegulator";
    public static String barredForReturnFlag = "barredForReturnFlag";
    //    public int beMoneyIn;
    //    public int beMoneyOut;
    public static String birthDate = "birthDate";
    //    public long blockingCode;
    public static String boughtPMchips = "boughtPMchips";
    //    public long brandsUsed;
    public static String cashBannedFlag = "cashBannedFlag";
    //    public String category;
    //    public static    String   chips                                   =         "chips" ;
    public static String city = "city";
    //    public static  ObjectNode   clearedMask                          =    ObjectNodeSchema   "clearedMask" ;
    //    public long clearedMask32;
    //    public long clearedMask64;
    public static String country = "country";
    //    public static  ObjectNode   cpp                                  =    ObjectNodeSchema   "cpp" ;
    public static String cppLifetime = "cppLifetime";
    public static String cppMilliCents = "cppMilliCents";
    public static String cppMonth = "cppMonth";
    public static String cppYear = "cppYear";
    public static String createdFromVirtualMachineFlag2 = "createdFromVirtualMachineFlag2";
    public static String currency = "currency";
    public static String customerDueDiligenceFlag3 = "customerDueDiligenceFlag3";
    public static String cvlExcludedFlag3 = "cvlExcludedFlag3";
    public static String cvlOptedInFlag3 = "cvlOptedInFlag3";
    //    public ObjectNode depositMask;
    //    public long depositMask32;
    //    public long depositMask64;
    public static String dfsFirstUsageFlag2 = "dfsFirstUsageFlag2";
    public static String dormantAccountFlag2 = "dormantAccountFlag2";
    public static String dormantByAutomationFlag2 = "dormantByAutomationFlag2";
    //    public String dummy;
    public static String everHadElevatedRiskLevelFlag3 = "everHadElevatedRiskLevelFlag3";
    public static String email = "email";
    public static String emailAlwaysValidateFlag2 = "emailAlwaysValidateFlag2";
    public static String emailAutoValidatedFlag2 = "emailAutoValidatedFlag2";
    public static String emailBouncedFlag = "emailBouncedFlag";
    public static String emailUnauthorizedFlag2 = "emailUnauthorizedFlag2";
    public static String emailVerifiedFlag = "emailVerifiedFlag";
    public static String emLocale = "emLocale";
    //    public String encrPwd;
    public static String facebookIntId = "facebookIntId";
    public static String firstDepositFlag = "firstDepositFlag";
    public static String firstDeposit = "firstDeposit";
    public static String firstName = "firstName";
    public static String firstSportsBetUserFlag3 = "firstSportsBetUserFlag3";
    public static String firstTransfer = "firstTransfer";
    //    public String fiscalCode;
    public static String fiscalCodeVerifiedFlag3 = "fiscalCodeVerifiedFlag3";
    public static String flags = "flags";
    public static String flags2 = "flags2";
    public static String flags3 = "flags3";
    public static String fpp = "fpp";
    public static String fppCents = "fppCents";
    public static String fppOneTime2016IncreaseFlag2 = "fppOneTime2016IncreaseFlag2";
    public static String fraudulentAccountFlag3 = "fraudulentAccountFlag3";
    public static String ftConversionDoneFlag3 = "ftConversionDoneFlag3";
    public static String ftKYCTrustedUserFlag3 = "ftKYCTrustedUserFlag3";
    public static String fullName = "fullName";
    public static String GDPRreadyFlag3 = "GDPRreadyFlag3";
    public static String generateTempPinOnEachLoginFlag3 = "generateTempPinOnEachLoginFlag3";
    //    public long gracePeriodUntilDummy;
    public static String guestAccount = "guestAccount";
    public static String hadValidatedPaymentMethodFlag3 = "hadValidatedPaymentMethodFlag3";
    public static String hasActiveFastDeposit = "hasActiveFastDeposit";
    //    public static  String   hasAdminOverrideDailyNetDepositLimitFlag3       =         "hasAdminOverrideDailyNetDepositLimitFlag3" ;
    //    public static  String   hasAdminOverrideMonthlyNetDepositLimitFlag3     =         "hasAdminOverrideMonthlyNetDepositLimitFlag3" ;
    public static String hasBuyinLimitEx = "hasBuyinLimitEx";
    public static String hasCasinoGameLimit = "hasCasinoGameLimit";
    public static String hasChallengeQuestionsFlag2 = "hasChallengeQuestionsFlag2";
    public static String hasDepositAttemptFlag2 = "hasDepositAttemptFlag2";
    public static String hasExtendedRelatedFlag3 = "hasExtendedRelatedFlag3";
    public static String hasFirstTransferFlag = "hasFirstTransferFlag";
    public static String hasFullTiltPairedAccount = "hasFullTiltPairedAccount";
    public static String hasIndividualLimitsFlag = "hasIndividualLimitsFlag";
    public static String hasLoginCoolOffLimitFlag3 = "hasLoginCoolOffLimitFlag3";
    public static String hasLoginTotalLimitFlag3 = "hasLoginTotalLimitFlag3";
    public static String hasLongSessionCoolOffLimitFlag3 = "hasLongSessionCoolOffLimitFlag3";
    public static String hasLossLimitFlag3 = "hasLossLimitFlag3";
    public static String hasMrmcAccountFlag = "hasMrmcAccountFlag";
    public static String hasNetDepositLimitFlag3 = "hasNetDepositLimitFlag3";
    public static String hasNonPmBalance = "hasNonPmBalance";
    public static String hasNonUsdAccountFlag = "hasNonUsdAccountFlag";
    public static String hasPendingDepositLimit = "hasPendingDepositLimit";
    public static String hasPendingGameLimit = "hasPendingGameLimit";
    public static String hasPlayingTimeLimit = "hasPlayingTimeLimit";
    public static String hasPokerDuelLimitFlag2 = "hasPokerDuelLimitFlag2";
    public static String hasPsExLossLimitFlag3 = "hasPsExLossLimitFlag3";
    public static String hasRelatedFlag = "hasRelatedFlag";
    public static String hasRmNokHeldDeposit = "hasRmNokHeldDeposit";
    public static String hasRollbackHistoryCalculatedFlag3 = "hasRollbackHistoryCalculatedFlag3";
    public static String hasRollbackHistoryFlag3 = "hasRollbackHistoryFlag3";
    public static String hasSideBetsLimitFlag3 = "hasSideBetsLimitFlag3";
    public static String hasSpendLimitFlag3 = "hasSpendLimitFlag3";
    public static String hasSportsAccumulatedLimitFlag2 = "hasSportsAccumulatedLimitFlag2";
    public static String hasSportsLossLimitFlag3 = "hasSportsLossLimitFlag3";
    public static String hasSportsSpendLimitFlag3 = "hasSportsSpendLimitFlag3";
    public static String hasSportsStakeLimit = "hasSportsStakeLimit";
    public static String hasSuperRelated = "hasSuperRelated";
    public static String hasTableLimitFlag = "hasTableLimitFlag";
    public static String hasTournLimit = "hasTournLimit";
    public static String hasTTicketsTotalCalculated = "hasTTicketsTotalCalculated";
    public static String hasUnclearedDepositsFlag = "hasUnclearedDepositsFlag";
    public static String hasWireAccountFlag = "hasWireAccountFlag";
    public static String hideCasinoGamesFlags2 = "hideCasinoGamesFlags2";
    public static String holdCashoutFlag = "holdCashoutFlag";
    public static String homeGamesPlayer = "homeGamesPlayer";
    //    public String idExtension;
    //    public String idStr;
    public static String idVerifiedFlag3 = "idVerifiedFlag3";
    public static String imageCheckedFlag = "imageCheckedFlag";
    public static String imageId = "imageId";
    public static String inGracePeriod_obsoleteFlag = "inGracePeriod_obsoleteFlag";
    //    public String installId;
    public static String intelliPokerRegisteredFlag = "intelliPokerRegisteredFlag";
    public static String ipAddrIsExemptFlag = "ipAddrIsExemptFlag";
    public static String isAffiliateFlag = "isAffiliateFlag";
    public static String itKeepRmMoneyOk = "itKeepRmMoneyOk";
    public static String itSuspendedClosed = "itSuspendedClosed";
    public static String KYCCompletedFlag3 = "KYCCompletedFlag3";
    public static String kycRequiredFlag3 = "kycRequiredFlag3";
    public static String lastDepositAmountLocalCurrency = "lastDepositAmountLocalCurrency";
    public static String lastDepositAmountUSD = "lastDepositAmountUSD";
    public static String lastDepositCompletedTime = "lastDepositCompletedTime";
    public static String lastDepositCurrency = "lastDepositCurrency";
    public static String lastName = "lastName";
    public static String licenseId = "licenseId";
    public static String licenseMobileVerifiedFlag3 = "licenseMobileVerifiedFlag3";
    //    public String licenseSpecificAmount3;
    //    public String licenseSpecificCounter2;
    //    public String licenseSpecificLimit1;
    public static String limitedLoginFlag = "limitedLoginFlag";
    public static String livenessVerifiedFlag3 = "livenessVerifiedFlag3";
    public static String locale = "locale";
    public static String loginBlockedGeoIpRuleFlags3 = "loginBlockedGeoIpRuleFlags3";
    //    public int ltFpp;
    //    public short ltFppCents;
    public static String marketBlackListFlag3 = "marketBlackListFlag3";
    //    public String mobile;
    public static String mobileVerified = "mobileVerified";
    //    public long nac2;
    public static String needWelcomeEmail = "needWelcomeEmail";
    public static String nemIdAuthenticated = "nemIdAuthenticated";
    public static String InstallIdForSmsDetected = "  InstallIdForSmsDetected";
    public static String nickNameCheckedFlag = "nickNameCheckedFlag";
    public static String noLoginEmailNotification = "noLoginEmailNotification";
    //    public String normUserId;
    public static String noSMSPasswordReset = "noSMSPasswordReset";
    public static String occupationVerifiedFlag3 = "occupationVerifiedFlag3";
    //    public long originalUserIntId;
    //    public ObjectNode overcreditMask;
    //    public long overcreditMask64;
    //    public int owedChips;
    public static String pastGracePeriod_obsoleteFlag = "pastGracePeriod_obsoleteFlag";
    public static String pepWatchScreenedAndValid = "pepWatchScreenedAndValid";
    public static String permanentBlacklistedFlag3 = "permanentBlacklistedFlag3";
    //    public String phone;
    //    public long platformUsed;
    //    public long playChips;
    //    public int playChips32;
    public static String playedRMCasinoGame = "playedRMCasinoGame";
    public static String playedRMGame = "playedRMGame";
    public static String playedRmLiveCasinoGameFlag3 = "playedRmLiveCasinoGameFlag3";
    public static String playingTimeLimitReached = "playingTimeLimitReached";
    //    public String prevUserId;
    public static String priv2AffiliateDNPC = "priv2AffiliateDNPC";
    public static String priv2AffiliateDNPP = "priv2AffiliateDNPP";
    public static String priv2AffiliateDoNotPay = "priv2AffiliateDoNotPay";
    public static String priv2AlwaysHighRiskRestriction = "priv2AlwaysHighRiskRestriction";
    public static String priv2BetaTester = "priv2BetaTester";
    public static String priv2BizAccount = "priv2BizAccount";
    public static String priv2BypassIpBlocking = "priv2BypassIpBlocking";
    public static String priv2CannotAddCurrencyAccount = "priv2CannotAddCurrencyAccount";
    public static String priv2CannotCreateHGClub = "priv2CannotCreateHGClub";
    public static String priv2CannotJoinHGClub = "priv2CannotJoinHGClub";
    public static String priv2CannotReceiveTransfer = "priv2CannotReceiveTransfer";
    public static String priv2CannotSendTransfer = "priv2CannotSendTransfer";
    public static String priv2CanRegisterMCTourns = "priv2CanRegisterMCTourns";
    public static String priv2ChatTempBannedByACM = "priv2ChatTempBannedByACM";
    public static String priv2DontShowPersonalInfo = "priv2DontShowPersonalInfo";
    public static String priv2ExcludeStellarReward = "priv2ExcludeStellarReward";
    public static String priv2ExemptFrom3DSecure = "priv2ExemptFrom3DSecure";
    public static String priv2HeadsUpTablesNotAllowed = "priv2HeadsUpTablesNotAllowed";
    public static String priv2HGNoEmails = "priv2HGNoEmails";
    public static String priv2HGShadowFounder = "priv2HGShadowFounder";
    public static String priv2HideMobileIconToOthers = "priv2HideMobileIconToOthers";
    public static String priv2HideUserInfo = "priv2HideUserInfo";
    public static String priv2IgnoreMicroTransfers = "priv2IgnoreMicroTransfers";
    public static String priv2LinkEmailToAccount = "priv2LinkEmailToAccount";
    public static String priv2MobileMarketingMessages = "priv2MobileMarketingMessages";
    public static String priv2MultiCurrBetaTester = "priv2MultiCurrBetaTester";
    public static String priv2NjTesting = "priv2NjTesting";
    public static String priv2NoAutoImageChange = "priv2NoAutoImageChange";
    public static String priv2NoAutomatedUnregister = "priv2NoAutomatedUnregister";
    public static String priv2NoCasinoLimitIncrease = "priv2NoCasinoLimitIncrease";
    public static String priv2NoCasinoPlay = "priv2NoCasinoPlay";
    public static String priv2NoDepositLimitIncrease = "priv2NoDepositLimitIncrease";
    public static String priv2NoFastDeposit = "priv2NoFastDeposit";
    public static String priv2NoHeadsUpSitNGo = "priv2NoHeadsUpSitNGo";
    public static String priv2NoHighRiskRestriction = "priv2NoHighRiskRestriction";
    public static String priv2NoHyperTurboSitNGo = "priv2NoHyperTurboSitNGo";
    public static String priv2NoLiveAssistance = "priv2NoLiveAssistance";
    public static String priv2NoPotLimitOmahaCashGames = "priv2NoPotLimitOmahaCashGames";
    public static String priv2NoPwdChangeReminder = "priv2NoPwdChangeReminder";
    public static String priv2NoSagTourns = "priv2NoSagTourns";
    public static String priv2NoSelfPLI = "priv2NoSelfPLI";
    public static String priv2NoSetupCQPrompt = "priv2NoSetupCQPrompt";
    public static String priv2NoSMSPasswordReset = "priv2NoSMSPasswordReset";
    public static String priv2NoTableLimitIncrease = "priv2NoTableLimitIncrease";
    public static String priv2NoTournLimitIncrease = "priv2NoTournLimitIncrease";
    public static String priv2NotQualifiedFirstTransfer = "priv2NotQualifiedFirstTransfer";
    public static String priv2NoZoomGames = "priv2NoZoomGames";
    public static String priv2Obsolete = "priv2Obsolete";
    public static String priv2OneTimeBypassConvLimits = "priv2OneTimeBypassConvLimits";
    public static String priv2PermanentClosuse = "priv2PermanentClosuse";
    public static String priv2PSRelated = "priv2PSRelated";
    public static String priv2Reserved6 = "priv2Reserved6";
    public static String priv2Reserved7 = "priv2Reserved7";
    public static String priv2SafeDepositMode = "priv2SafeDepositMode";
    public static String priv2ShowNoChatTooltip = "priv2ShowNoChatTooltip";
    public static String priv2ShowVipStatusToOthers = "priv2ShowVipStatusToOthers";
    public static String priv2SuspendRM = "priv2SuspendRM";
    public static String priv2TeamPro = "priv2TeamPro";
    public static String priv2TransferAffiliate = "priv2TransferAffiliate";
    public static String priv2UserGlobalMute = "priv2UserGlobalMute";
    public static String priv3AvailableForReuse = "priv3AvailableForReuse";
    public static String priv3BadBeatCutoff = "priv3BadBeatCutoff";
    public static String priv3BlockPMPurchase = "priv3BlockPMPurchase";
    public static String priv3BypassMAAAutoActions = "priv3BypassMAAAutoActions";
    public static String priv3BypassNAC2 = "priv3BypassNAC2";
    public static String priv3BypassOTP = "priv3BypassOTP";
    public static String priv3CasinoPremiumPlayer = "priv3CasinoPremiumPlayer";
    public static String priv3CasinoVIP = "priv3CasinoVIP";
    public static String priv3DoNotPayBonus = "priv3DoNotPayBonus";
    public static String priv3ExtRegulator = "priv3ExtRegulator";
    public static String priv3FppBundles = "priv3FppBundles";
    public static String priv3IncidentReportFiled = "priv3IncidentReportFiled";
    public static String priv3KeepYoungUserGroup = "priv3KeepYoungUserGroup";
    public static String priv3NoAllInCashout = "priv3NoAllInCashout";
    public static String priv3NoCashoutCancellation = "priv3NoCashoutCancellation";
    public static String priv3NoDFSPlay = "priv3NoDFSPlay";
    public static String priv3NoEwlSportsPlay = "priv3NoEwlSportsPlay";
    public static String priv3NoHTML5Client = "priv3NoHTML5Client";
    public static String priv3NoKOTourns = "priv3NoKOTourns";
    public static String priv3NoLeaderBoard = "priv3NoLeaderBoard";
    public static String priv3NoLossLimitIncrease = "priv3NoLossLimitIncrease";
    public static String priv3NoMailListCasino = "priv3NoMailListCasino";
    public static String priv3NoMailListPoker = "priv3NoMailListPoker";
    public static String priv3NoMailListSports = "priv3NoMailListSports";
    public static String priv3NoPlayTimeIncrease = "priv3NoPlayTimeIncrease";
    public static String priv3NoPowerUpPlay = "priv3NoPowerUpPlay";
    public static String priv3NoSideBets = "priv3NoSideBets";
    public static String priv3NoSportLiveAlert = "priv3NoSportLiveAlert";
    public static String priv3NoSportsBonus = "priv3NoSportsBonus";
    public static String priv3NoSportsLimitIncrease = "priv3NoSportsLimitIncrease";
    public static String priv3NoSportsPlay = "priv3NoSportsPlay";
    public static String priv3NoSuggestedDeposit = "priv3NoSuggestedDeposit";
    public static String priv3NoSurveyInvites = "priv3NoSurveyInvites";
    public static String priv3NoUnfoldCashGames = "priv3NoUnfoldCashGames";
    public static String priv3NoUpsell = "priv3NoUpsell";
    public static String priv3NoWithdrawal = "priv3NoWithdrawal";
    public static String priv3PMPremiumPlayer = "priv3PMPremiumPlayer";
    public static String priv3PokerPremiumPlayer = "priv3PokerPremiumPlayer";
    public static String priv3PspcDisplay = "priv3PspcDisplay";
    public static String priv3SportsPremiumPlayer = "priv3SportsPremiumPlayer";
    public static String priv3SportsVip = "priv3SportsVip";
    public static String priv3SportTrader = "priv3SportTrader";
    public static String priv3StaffPlayAccount = "priv3StaffPlayAccount";
    public static String priv3UsesCompetitor = "priv3UsesCompetitor";
    public static String privAdmin = "privAdmin";
    public static String privBonusAfterCashout = "privBonusAfterCashout";
    public static String privBypassVelocityControl = "privBypassVelocityControl";
    public static String privChangeImage = "privChangeImage";
    public static String privChat = "privChat";
    public static String privDoNotSendTournWinnerEmail = "privDoNotSendTournWinnerEmail";
    public static String privDontShowWhere = "privDontShowWhere";
    public static String privDuplicate = "privDuplicate";
    public static String privEarlyCashout = "privEarlyCashout";
    public static String privHidePersonalInfo = "privHidePersonalInfo";
    public static String privHighRoller = "privHighRoller";
    public static String privileges = "privileges";
    public static String privileges2 = "privileges2";
    public static String privileges3 = "privileges3";
    public static String privInstaClearCashout = "privInstaClearCashout";
    public static String privNoAutoBan = "privNoAutoBan";
    public static String privNoBanByCountry = "privNoBanByCountry";
    public static String privNoCityChange = "privNoCityChange";
    public static String privNoMailList = "privNoMailList";
    public static String privNotSpendUncleared = "privNotSpendUncleared";
    public static String privPlay = "privPlay";
    public static String privRequestTourn = "privRequestTourn";
    public static String privRollbackOverride = "privRollbackOverride";
    public static String privSelfExcluded = "privSelfExcluded";
    public static String privShowImage = "privShowImage";
    public static String privSuperHighRoller = "privSuperHighRoller";
    public static String privTestCashier = "privTestCashier";
    public static String privTimeoutAllIn = "privTimeoutAllIn";
    public static String privTMoneyTrader = "privTMoneyTrader";
    public static String privTransferVerified = "privTransferVerified";
    public static String privVip = "privVip";
    public static String privVipTest = "privVipTest";
    public static String pspGenerated = "pspGenerated";
    public static String pspRequiredFlag = "pspRequiredFlag";
    public static String pwdResetCodeGeneratedFlag3 = "pwdResetCodeGeneratedFlag3";
    public static String rateMobileAppFlag2 = "rateMobileAppFlag2";
    public static String realMoneyOkFlag = "realMoneyOkFlag";
    public static String registered = "registered";
    public static String registeredInRegulatorFlag3 = "registeredInRegulatorFlag3";
    public static String RMPlayerDepositTransferFlag = "RMPlayerDepositTransferFlag";
    public static String rsaActivated = "rsaActivated";
    public static String rsaRequiredFlag = "rsaRequiredFlag";
    public static String security3DSTriggerFlag3 = "security3DSTriggerFlag3";
    public static String sex = "sex";
    public static String showAMLVerifiedModalFlag3 = "showAMLVerifiedModalFlag3";
    public static String showSelfExclusionExpiredDialogFlag3 = "showSelfExclusionExpiredDialogFlag3";
    //    public String sid;
    //    public static  String   siteId                                     =         "siteId" ;
    public static String smsMarketingFlag = "smsMarketingFlag";
    public static String smsValidationForNewInstallId = "smsValidationForNewInstallId";
    //    public ObjectNode spp;
    public static String sppLifetime = "sppLifetime";
    public static String sppMonth = "sppMonth";
    public static String sppYear = "sppYear";
    public static String state = "state";
    public static String strongAuthReqd = "strongAuthReqd";
    public static String subsequentAccount = "subsequentAccount";
    //    public int tChips;
    public static String tempPINFromAdminMassAssignFlag3 = "tempPINFromAdminMassAssignFlag3";
    public static String tempPINFromFailedLoginsFlag3 = "tempPINFromFailedLoginsFlag3";
    public static String tempPINFromNewDeviceFlag3 = "tempPINFromNewDeviceFlag3";
    public static String timezone = "timezone";
    //    public short unique;
    public static String usedSelfExclusionFlag = "usedSelfExclusionFlag";
    //    public ObjectNode userData;
    public static String userHasDummyEmailFlag2 = "userHasDummyEmailFlag2";
    public static String userId = "userId";
    public static String userIntId = "userIntId";
    public static String userIsArchivedFlag2 = "userIsArchivedFlag2";
    public static String valuePropMessageDisplayedFlags3 = "valuePropMessageDisplayedFlags3";
    public static String verifiedByRegulator_NEVER_USED = "verifiedByRegulator_NEVER_USED";
    public static String verifiedForMarketingFlag3 = "verifiedForMarketingFlag3";

    public static String vppMinimumEarnedInternal = "vppMinimumEarnedInternal";
    public static String walletCAD = "walletCAD";
    public static String walletEUR = "walletEUR";
    public static String walletGBP = "walletGBP";
    public static String walletINR = "walletINR";
    public static String walletRON = "walletRON";
    public static String walletSEK = "walletSEK";
    public static String walletUSD = "walletUSD";
    public static String zipCode = "zipCode";

}